### ISSUE TITLE
Stopwatch laps hard to read

### ISSUE THREAD

**Issue by cassidyjames** [sgpthomas/hourglass#96] opened 2020-09-14 23:51 UTC
1.2.2 from AppCenter

![image](https://user-images.githubusercontent.com/611168/93149127-c9e41100-f6b2-11ea-9c26-c615f377456b.png)

**Comment by ryonakano** [comment] 2020-09-15 00:34
Closing as a duplicate of #55. I'll take a look at this soon :eyes:

**Closed by ryonakano** 2020-09-15 00:34 UTC

**Comment by cassidyjames** [comment] 2020-09-15 15:33
Ah, my bad! I thought this was a new issue with 1.2.2 so I didn't even search for duplicates. :facepalm:
