### ISSUE TITLE
Alarm tab doesn't accept new alarm 

### ISSUE THREAD

**Issue by Tutmos** [sgpthomas/hourglass#83] opened 2020-06-19 14:50 UTC
After clicking ADD button a new dialog is raised.
I set up a new alarm, added a new title, and clicked the green button Create.
No new alarm was set up.

hint: I think this bug is it related to the date, my date is in Cyrillic and its something like - юни 19 2020, and suppose this confuse the app.

p.s I used the same app in Loki and it was working perfectly. Now in Hera I noticed this bug

**Comment by ryonakano** [comment] 2020-06-19 22:18
Thank you for your report, but this seems to be a duplicate of #71.

It may be due to DBus or that kind of component; I tested the app both on Hera and on Daily (based on Ubuntu 20.04 LTS), and it does work perfectly on Daily, although the app is completely the same version. :thinking:

**Closed by ryonakano** 2020-06-19 22:18 UTC
