### ISSUE TITLE
Can't set timer on elemenary OS.

### ISSUE THREAD

**Issue by purringChaos** [sgpthomas/hourglass#78] opened 2020-05-07 14:22 UTC
Installed from the software centre
```
** (process:21236): CRITICAL **: 15:21:12.351: hourglass_daemon_saved_alarms_get_alarms: assertion 'self != NULL' failed
[FATAL 15:21:19.805373] file /build/com.github.sgpthomas.hourglass-1.2.1/src/Widgets/AlarmTimeWidget.vala: line 196: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.github.sgpthomas.hourglass was not provided by any .service files (g-dbus-error-quark, 2)
```

**Comment by NamedKitten** [comment] 2020-05-07 14:27
```
[New Thread 0x7fffe7fff700 (LWP 28322)]
** Message: 15:27:20.677: HourglassDaemon.vala:39: Hourglass-Daemon started
[New Thread 0x7fffe77fe700 (LWP 28323)]
** Message: 15:27:20.677: AlarmManager.vala:28: Initiating Alarm Manager

** (process:28317): CRITICAL **: 15:27:20.677: hourglass_daemon_saved_alarms_get_alarms: assertion 'self != NULL' failed

Thread 1 "com.github.sgpt" received signal SIGSEGV, Segmentation fault.
0x00005555555582f9 in hourglass_daemon_alarm_manager_load_alarm_list (Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
self=) at /home/kitteh/hourglass/src/Daemon/AlarmManager.vala:79
79	            foreach (string s in saved_alarms.alarms) { //loop through all entries in schema
(gdb) bt
#0  0x00005555555582f9 in hourglass_daemon_alarm_manager_load_alarm_list (self=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
) at /home/kitteh/hourglass/src/Daemon/AlarmManager.vala:79
#1  0x0000555555557bbd in hourglass_daemon_alarm_manager_construct (object_type=200) at /home/kitteh/hourglass/src/Daemon/AlarmManager.vala:31
#2  0x0000555555557bd4 in hourglass_daemon_alarm_manager_new () at /home/kitteh/hourglass/src/Daemon/AlarmManager.vala:27
#3  0x000055555555b5d2 in hourglass_daemon_hourglass_alarm_daemon_real_startup (base=0x55555577d0b0) at /home/kitteh/hourglass/src/Daemon/HourglassDaemon.vala:43
#4  0x00007ffff74db10d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff74ee12e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff74f6715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff74f712f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff77c12c2 in g_application_register () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x000055555555ba53 in hourglass_daemon_main (args=0x7fffffffde78, args_length1=1) at /home/kitteh/hourglass/src/Daemon/HourglassDaemon.vala:77
#10 0x000055555555bb93 in main (argc=1, argv=0x7fffffffde78) at /home/kitteh/hourglass/src/Daemon/HourglassDaemon.vala:72
(gdb) 

```

**Comment by NamedKitten** [comment] 2020-05-07 14:28
```
kitteh@uwu:~/hourglass/build$ com.github.sgpthomas.hourglass
[DEBUG 15:28:05.758163] Settings.vala:164: Loading settings from schema 'com.github.sgpthomas.hourglass.saved'
[DEBUG 15:28:05.758738] Settings.vala:164: Loading settings from schema 'org.gnome.desktop.interface'
[INFO 15:28:05.758912] Hourglass.vala:74: starting daemon
[FATAL 15:28:05.765634] file /home/kitteh/hourglass/src/Services/DBusManager.vala: line 46: unexpected error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.github.sgpthomas.hourglass was not provided by any .service files (g-dbus-error-quark, 2)
[INFO 15:28:05.770394] StyleManager.vala:30: Loaded /com/github/sgpthomas/hourglass/style/text.css
[INFO 15:28:05.771237] StyleManager.vala:30: Loaded /com/github/sgpthomas/hourglass/style/elements.css
[FATAL 15:28:05.776388] file /home/kitteh/hourglass/src/Widgets/AlarmTimeWidget.vala: line 165: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.github.sgpthomas.hourglass was not provided by any .service files (g-dbus-error-quark, 2)
[FATAL 15:28:05.777550] file /home/kitteh/hourglass/src/Widgets/AlarmTimeWidget.vala: line 165: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.github.sgpthomas.hourglass was not provided by any .service files (g-dbus-error-quark, 2)
** Message: 15:28:05.782: HourglassDaemon.vala:39: Hourglass-Daemon started
** Message: 15:28:05.782: AlarmManager.vala:28: Initiating Alarm Manager

** (process:28374): CRITICAL **: 15:28:05.783: hourglass_daemon_saved_alarms_get_alarms: assertion 'self != NULL' failed
[INFO 15:28:05.832512] TimerTimeWidget.vala:172: starting
[FATAL 15:28:05.954088] file /home/kitteh/hourglass/src/Widgets/Counter.vala: line 110: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.github.sgpthomas.hourglass was not provided by any .service files (g-dbus-error-quark, 2)
kitteh@uwu:~/hourglass/build$ 
```

**Comment by ryonakano** [comment] 2020-05-11 10:38
Closing as a duplicate of #71. Anyway, thank you for your reporting and investigation.

**Closed by ryonakano** 2020-05-11 10:38 UTC
